#!/usr/bin/env python3

import rospy

import smbus2
import bme280

from avrhydroponics.msg import AirMetrics

ADDRESS = 0x76

class Node(object):
    def __init__(self):
        rospy.init_node("bme280_node", disable_signals=True)
        self.bus = smbus2.SMBus(1)
        self.calib_data = bme280.load_calibration_params(self.bus, ADDRESS)
        self.publisher = rospy.Publisher("air_metrics", AirMetrics, queue_size=10)

    def run(self):
        rate = rospy.Rate(1)
        while not rospy.is_shutdown():
            data = bme280.sample(self.bus, ADDRESS, self.calib_data)
            msg = AirMetrics()
            msg.header.stamp = rospy.Time.now()
            msg.temperature = data.temperature
            msg.humidity = data.humidity
            msg.pressure = data.pressure
            self.publisher.publish(msg)
            try:
                rate.sleep()
            except KeyboardInterrupt:
                rospy.signal_shutdown("Keyboard Interrupt")

def main():
    node = Node()
    node.run()

if __name__ == "__main__":
    main()