#!/usr/bin/env python
# -*- coding: utf-8 -*-
import RPi.GPIO as GPIO
import rospy
from avrhydroponics.srv import SetRelay


class Node(object):
    def __init__(self):
        rospy.init_node("relay_node")
        rospy.on_shutdown(self.on_shutdown)
        self.relays = (5, 6, 13, 19, 26)
        GPIO.setmode(GPIO.BCM)
        self.init_gpio()
        rospy.Service("set_relay", SetRelay, self.on_set_relay)

    def init_gpio(self):
        for relay in self.relays:
            GPIO.setup(relay, GPIO.OUT)
            GPIO.output(relay, GPIO.HIGH)

    def on_set_relay(self, req):
        relay = min(max(0, req.relay), 7)
        if req.state:
            GPIO.output(self.relays[relay], GPIO.LOW)
        else:
            GPIO.output(self.relays[relay], GPIO.HIGH)
        return dict(success=True)

    def on_shutdown(self):
        self.init_gpio()
        GPIO.cleanup()


def main():
    node = Node()
    rospy.spin()


if __name__ == "__main__":
    main()
